global:
  # 抓取间隔（越小越实时，但数据量越大）
  scrape_interval: 5s

  # 规则计算间隔（告警用）
  evaluation_interval: 5s


# 告警/规则文件目录（对应挂载）
rule_files:
  - /etc/prometheus/rules/*.yml


scrape_configs:

  # 本机监控
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.128.228:9100']
        labels:
          instance: 'node-192-168-128-228'

    # 👉 说明：
    # node_exporter 默认端口 9100
    # 这里写的是“宿主机IP”，不是容器名
    # 因为 node-exporter 用的是 host 网络

  - job_name: 'postgres'
    static_configs:
      - targets: ['192.168.128.228:9187']

  # LLM模型监控
  - job_name: 'vllm-qwen3-32b'
    static_configs:
      - targets: ['192.168.129.20:8801']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 59.204.85.130:9093   # 如果是host网络，用宿主机IP
